let a = alert (10);
let b = alert (20);
let year = "год выпуска первого Айфон - 2007";
alert (year);
let creation = "создатель языка Java Script - Брендан Эйх";
alert (creation);
let c = 10;
let d = 2;
let up = 2;
let resultsum = c + d;
alert (c);
alert (d);
alert (resultsum);
let resultdiff = c - d;
alert (resultdiff);
let resultmult = c * d;
alert (resultmult);
let resultdivis = c / d;
alert (resultdivis);
const result = 2 ** 5;
alert (result);
let f = 9;
let g = 2;
let newresult = f % g;
alert (newresult);

let num = 1;
num += 5;
num -= 3;
num *= 7;
num /= 3;
++num;
--num;
alert(num);